module.exports = {
    moduleFileExtensions: ['js', 'json', 'ts'],
    rootDir: 'src',
    testRegex: '.*\\.spec\\.ts$',
    transform: {
        '^.+\\.(t|j)s$': '@swc/jest',
    },
    collectCoverageFrom: [
        '**/*.(t|j)s',
        '!**/*.spec.ts',
        '!**/*.interface.ts',
        '!**/*.dto.ts',
        '!**/*.entity.ts',
        '!**/*.enum.ts',
        '!**/*.decorator.ts',
        '!**/*.guard.ts',
        '!**/*.interceptor.ts',
        '!**/*.pipe.ts',
        '!**/*.filter.ts',
        '!**/*.strategy.ts',
        '!**/*.middleware.ts',
        '!**/main.ts',
        '!**/app.module.ts',
    ],
    coverageDirectory: '../coverage',
    testEnvironment: 'node',
    moduleNameMapper: {
        '^src/(.*)$': '<rootDir>/$1',
    },
    setupFilesAfterEnv: ['<rootDir>/../test/setup.ts'],
    testTimeout: 10000,
    verbose: true,
    forceExit: true,
    clearMocks: true,
    resetMocks: true,
    restoreMocks: true,
};