export default {
    displayName: 'Applications Module',
    preset: '../../jest.preset.js',
    testEnvironment: 'node',
    transform: {
        '^.+\\.[tj]s$': ['ts-jest', { tsconfig: '<rootDir>/tsconfig.spec.json' }],
    },
    moduleFileExtensions: ['ts', 'js', 'html'],
    coverageDirectory: '../../coverage/applications',
    collectCoverageFrom: [
        'src/**/*.(t|j)s',
        '!src/**/*.spec.ts',
        '!src/**/*.interface.ts',
        '!src/**/*.dto.ts',
        '!src/**/*.entity.ts',
        '!src/**/*.enum.ts',
        '!src/**/*.module.ts',
        '!src/**/*.decorator.ts',
        '!src/**/*.guard.ts',
        '!src/**/*.interceptor.ts',
        '!src/**/*.pipe.ts',
        '!src/**/*.filter.ts',
        '!src/**/*.strategy.ts',
        '!src/**/*.middleware.ts',
        '!src/**/*.config.ts',
        '!src/**/*.constant.ts',
        '!src/**/*.type.ts',
        '!src/**/*.interface.ts',
        '!src/**/*.mock.ts',
        '!src/**/*.stub.ts',
        '!src/**/*.fixture.ts',
        '!src/**/*.test.ts',
        '!src/**/*.spec.ts',
        '!src/**/index.ts',
        '!src/**/main.ts',
        '!src/**/app.module.ts',
        '!src/**/app.controller.ts',
        '!src/**/app.service.ts',
    ],
    testMatch: [
        '<rootDir>/src/**/*.spec.ts',
        '<rootDir>/src/**/*.test.ts',
    ],
    setupFilesAfterEnv: ['<rootDir>/../../test/setup-unit.ts'],
    testTimeout: 10000,
    coverageReporters: ['text', 'lcov', 'html'],
    coverageThreshold: {
        global: {
            branches: 80,
            functions: 80,
            lines: 80,
            statements: 80,
        },
    },
    moduleNameMapping: {
        '^@/(.*)$': '<rootDir>/src/$1',
    },
    clearMocks: true,
    restoreMocks: true,
    resetMocks: true,
};
